spring:
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changeLog-master.xml
  datasource:
    url: jdbc:h2:file:~/.database/photoDb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

